package graphgo

const (
	NODE_LABEL_EDGE_LABEL = "HAS_LABEL"

	ERR_NODE_NOT_FOUND          = "ERR_NODE_NOT_FOUND"
	ERR_EDGE_NOT_FOUND          = "ERR_EDGE_NOT_FOUND"
	ERR_NODE_PROP_NOT_FOUND     = "ERR_NODE_PROP_NOT_FOUND"
	ERR_EDGE_PROP_NOT_FOUND     = "ERR_EDGE_PROP_NOT_FOUND"
	ERR_NODE_INE_MISSING_EDGES  = "ERR_NODE_INE_MISSING_EDGES"
	ERR_NODE_OUTE_MISSING_EDGES = "ERR_NODE_OUTE_MISSING_EDGES"
	ERR_CONNECTED_NODE          = "ERR_CONNECTED_NODE"
	ERR_NO_NODE_LEGACY_RECORD   = "ERR_NO_NODE_LEGACY_RECORD"
	ERR_NO_EDGE_LEGACY_RECORD   = "ERR_NO_EDGE_LEGACY_RECORD"
)
