package graphgo

const (
	NODE_LABEL_EDGE_LABEL = "HAS_LABEL"
	KEY_SEPARATOR         = "::"

	ERR_NODE_NOT_FOUND      = "ERR_NODE_NOT_FOUND"
	ERR_EDGE_NOT_FOUND      = "ERR_EDGE_NOT_FOUND"
	ERR_NODE_PROP_NOT_FOUND = "ERR_NODE_PROP_NOT_FOUND"
	ERR_EDGE_PROP_NOT_FOUND = "ERR_EDGE_PROP_NOT_FOUND"

	ERR_NODE_INE_MISSING_EDGES  = "ERR_NODE_INE_MISSING_EDGES"
	ERR_NODE_OUTE_MISSING_EDGES = "ERR_NODE_OUTE_MISSING_EDGES"
)
